version: '3.7'
# DevelopMent
services:
  repeat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env

  repeat-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'repeat-nest'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  # repeat-redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
